### ISSUE TITLE
discussion on EEVblog

### ISSUE THREAD

**Issue by FrankBuss** [lkdjiin/electr#2]
For those who don't have a github account, and for easier commenting and discussing than in "issues", I created a posting on EEVblog:
http://www.eevblog.com/forum/projects/electr-interactive-language-for-electronic-formulas-%28on-the-command-line%29/

**Comment by lkdjiin** [comment]
This is great! Thank you!

**Comment by lkdjiin** [comment]
No new messages since 2 months, I think it's time to close this one.

Thanks again ;)
