### ISSUE TITLE
Replace the actual in-house lexer/tokenizer with a RLTK grammar

### ISSUE THREAD

**Issue by bankair** [lkdjiin/electr#20]
Using RLTK could help to give a bit more structure to the code.

https://github.com/chriswailes/RLTK

**Comment by lkdjiin** [comment]
It's unlikely that it happens, for 3 reasons.

1) I've some experience with such libraries, and I always ended to struggle with them. Every single time. There is always a moment when you want to do something different.

2) It works as is. If you think it needs some more structure, one can add more structure without adding new things.

3) This current ruby version is just for prototyping the language. After the version 1.0 I'll target the C version. Indeed I already experimenting with C… And so I'm reluctant to add new technologies.

Actually what do you think by «more structure» ?

**Comment by bankair** [comment]
Hi mate,

When I say 'more structure', I'm not talking about modularity (you did a great job at splitting responsibilities). What I'm thinking of is that the project could be easier to maintain if the parsing was materialized in a grammar (and not split over several files).

For example, allowing the value format to be '1mA' and '1 mA' took me (and I'm clearly not done yet) 3 files to update (token, tokenizer and value) without taking spec files into account.

Would you mind that I try an experiment on that subject, if I find some time (which is very very unlikely :smile: ) ?

**Comment by lkdjiin** [comment]
Ok, I see your point now.

On the one hand, having to modify several files for adding things can be bad, you're right. On the other hand (here) this is the price to pay for freedom ;) I mean, to not include all in one libraries… And I think there is a general pattern to follow when adding/modifying the (ok, kinda hidden) grammar : start to add/modify a tokenizer spec and just be guided by the fails.

And of course, you can experiment as much as you want ;) Just keep in mind that I've had really bad times with parser generators, so I would probably not be objective.

**Comment by bankair** [comment]
I can understand that :)

Le lun. 9 nov. 2015 à 11:06, Xavier Nayrac notifications@github.com a
écrit :
