### ISSUE TITLE
Definitely a good-sounding idea, if the grammar can be made intuitively unambiguous

### ISSUE THREAD

**Issue by i336** [lkdjiin/electr#3]
I'm not into electronics that much, but in spite of that I can definitely see this going places and being incredibly useful.

- As for what I mean by unambiguous language, I mean that you need to figure out how to juggle "normal calculator functionality" and electronics-oriented functionality, so that I'd have a way to distinguish "300K" as "300,000" from "300K" as in "300K&ohm; resistor," where each would produce different results.

- You should put together a [Jupyter](http://jupyter.org) kernel for it, so people don't have to stare at/use it via `cmd.exe` on Windows (ewww :P)

- If you write this in Perl (yes, Perl...), you could provide it to a few bazillion people via [DuckDuckGo's server-side instant-answer architecture](http://perltricks.com/article/189/2015/8/22/Writing-DuckDuckGo-plugins-just-got-easier)... \**nods*\* eheheh. YEAH. :D

**Comment by lkdjiin** [comment]
1) I'm not sure to understand what you mean. I don't see any ambiguity here:

- 300K and 300,000 are the same value. 300K is Ohms and 300,000 is just the constant.
- K and KΩ could be synonym, why not, but it's surely faster to type just K ;)

2) I should definitely check this Jupyter thing… Thanks for pointing this.

3) Perl? Sorry, no I'm not going to do that ;) But I like a lot this idea of a plugin.

**Comment by i336** [comment]
To be honest, I can't think of a specific scenario where it might be truly impossible to describe a calculation without ambiguity getting in the way; I only have a vague sense that it might crop it. Perhaps it won't be a problem :)

Someone mentioned a similar ambiguity-related issue on [the HN post](https://news.ycombinator.com/item?id=10132913) ("it's not always evident what unit you want show after a calculation") - this sort of gets at what I mean.

**Comment by lkdjiin** [comment]
I think I understand you better now ;)
As I see this issue, it won't be a problem: showing the unit after calculation will be a nice to have, not a must have.
