### ISSUE TITLE
Passing a suggestion on: "don't use '~v', people will keep confusing it with 'V' at first glance"

### ISSUE THREAD

**Issue by i336** [lkdjiin/electr#5]
From https://www.reddit.com/r/electronics/comments/3iokaw/electr_is_an_concept_for_a_commandline_utility/cuiazdk

**Comment by lkdjiin** [comment]
Good suggestion, I was not too confident with `v~` anyway ;)

- Just `~`?
- `sq`?
- `sr`?
- I don't like the idea to type `sqrt`

**Comment by martindemello** [comment]
maybe \? it needn't look like a square root symbol; it just needs to be convenient to use and nice to attach to a number on the same level as a unary -. `\2` doesn't read too badly.

**Comment by FrankBuss** [comment]
I don't think you need it often, so sqr(x) would be fine, just like other functions like sin(x) or cos(x). It is just one character more than v~, but easier to type, read and remember. Of course, (x)^0.5 should be allowed, too.

**Comment by lkdjiin** [comment]
@FrankBuss You made a good point. An extended feature could be to allow abbreviation when they are not ambiguous. For example `sqrt`, `sqr` and `sq` will work, but `s` won't because one cannot tell if it is `sqrt` or `sin`.

**Comment by lkdjiin** [comment]
@martindemello `\` is the escape char, so I don't think it could be a good option ;)

**Comment by martindemello** [comment]
hah, i guess not :) why does a calculator need an escape character, though?

**Comment by lkdjiin** [comment]
@martindemello I don't want to restrict Electr to a calculator, but even in this case one could get in troubles using `\`.  Suppose you have an option (-e) to pass an expression to Electr directly on the command line. To compute the square root of 2 should it be:

    $ electr -e \2

or

    $ electr -e \\2

**Comment by martindemello** [comment]
ah yes, i forgot about the -e use case. i feel sqrt(2) at the least comes up often enough that there should be lightweight syntactic support for it, but ascii symbols are sadly rather limited.
