### ISSUE TITLE
see if frink helps

### ISSUE THREAD

**Issue by martindemello** [lkdjiin/electr#7]
https://futureboy.us/frinkdocs/

it's java based, but it's a programming language that is already mathematically oriented and unit aware.

**Comment by lkdjiin** [comment]
I definitely have to give Frink a try.

**Comment by lkdjiin** [comment]
By the way Frink isn't open source.

**Comment by martindemello** [comment]
oh, didn't realise that! pretty disappointing; no wonder it doesn't have more mindshare.
